name: Build and Deploy

on:
  release:
    types: [ published ]

env:
  build-output: sakura-publish

jobs:
  sentry-release:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://dragonfruit.network/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_ORG: dragonfruit
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          projects: sakura
          ignore_missing: true
          version: ${{ github.ref_name }}

  website-package:
    runs-on: ubuntu-latest
    
    permissions: 
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build Program
        run: dotnet publish -c Release -p:Version=${{ github.event.release.tag_name }} DragonFruit.Sakura
        
      - name: Package Output
        run: dotnet pack -c Release -p:Version=${{ github.event.release.tag_name }} -o ./packages --no-build DragonFruit.Sakura
        
      - name: Upload Package
        run: dotnet nuget push -s https://nuget.pkg.github.com/dragonfruitnetwork/index.json -k ${{ github.token }} ./packages/*.nupkg
  
  windows-iis:
    runs-on: windows-latest
    
    permissions:
      contents: write
    
    needs:
      - sentry-release

    environment:
      name: production
      url: https://dragonfruit.network/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Program
        run: dotnet publish -c Release -p:Version=${{ github.event.release.tag_name }} -p:PublishProfile=Web.pubxml DragonFruit.Sakura.Host

      - name: Archive Output
        run: Compress-Archive -Path .\DragonFruit.Sakura.Host\bin\publish\* -DestinationPath Sakura-${{ github.event.release.tag_name }}.zip

      - name: Upload Deploy Package
        uses: softprops/action-gh-release@v1
        with:
          files: Sakura-${{ github.event.release.tag_name }}.zip