name: Build and Deploy

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://dragonfruit.network/
          
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet pack -c Release -o ${{ github.workspace }} -p:Version=${{ github.ref_name }} DragonFruit.Sakura/DragonFruit.Sakura.csproj

      - name: Publish .nupkg
        run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_KEY }} --skip-duplicate

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_ORG: dragonfruit
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          projects: sakura
          ignore_missing: true
          version: ${{ github.ref_name }}
