name: Build and Deploy

on:
  release:
    types: [ published ]

permissions:
  contents: write
  
env:
  DEPLOY_USER: sakura-deploy
  DEPLOY_EMAIL: inbox@dragonfruitnetwork
  DEPLOY_FOLDER: ~/out/wwwroot

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - id: sakura-deploy-key
        name: Get Deploy Token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore NuGet Packages
        run: dotnet restore
        
      - name: Prepare Output Directory
        run: mkdir ~/out
        
      - name: Build Project
        run: dotnet publish ./DragonFruit.Sakura/DragonFruit.Sakura.csproj --configuration Release -p:Version=${{ github.ref_name }} -o ~/out
        
      - name: Publish (Preview)
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          single-commit: true
          folder: ${{ env.DEPLOY_FOLDER }}
          git-config-name: ${{ env.DEPLOY_USER }}
          git-config-email: ${{ env.DEPLOY_EMAIL }}
          token: ${{ steps.sakura-deploy-key.outputs.token }}
          repository-name: dragonfruitnetwork/sakura-preview
        
      - name: Publish (Production)
        if: "!github.event.release.prerelease"
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          single-commit: true
          folder: ${{ env.DEPLOY_FOLDER }}
          git-config-name: ${{ env.DEPLOY_USER }}
          git-config-email: ${{ env.DEPLOY_EMAIL }}
          token: ${{ steps.sakura-deploy-key.outputs.token }}
          repository-name: dragonfruitnetwork/sakura-production
