name: Build and Deploy

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://preview.dragonfruit.network
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - id: sakura-deploy-key
        name: Get Deploy Token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore NuGet Packages
        run: dotnet restore
        
      - name: Prepare Output Directory
        run: mkdir ~/out
        
      - name: Build Project
        run: dotnet publish ./DragonFruit.Sakura/DragonFruit.Sakura.csproj --configuration Release -p:Version=${{ github.ref_name }} -o ~/out
        
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: master
          single-commit: true
          folder: ~/out/wwwroot
          git-config-name: sakura-deploy
          git-config-email: inbox@dragonfruit.network
          repository-name: dragonfruitnetwork/sakura-web
          token: ${{ steps.sakura-deploy-key.outputs.token }}
