name: Build and Deploy

on:
  release:
    types: [ published ]

env:
  build-output: sakura-publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://dragonfruit.network/
          
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Create build output folder
        run: mkdir ${{ env.build-output }}

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet publish -c Release -o ${{ env.build-output }} -p:Version=${{ github.ref_name }} DragonFruit.Sakura/DragonFruit.Sakura.csproj

      - id: meta
        name: Create metadata
        uses: docker/metadata-action@v4
        with:
          images: dragonfruitdotnet/website
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=sha

      - name: Dockerise
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.build-output }}
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          file: DragonFruit.Sakura.Host/Dockerfile

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_ORG: dragonfruit
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          projects: sakura
          ignore_missing: true
          version: ${{ github.ref_name }}
